### PR TITLE
added default port

### PR DESCRIPTION
**Pull request by edewit**

### CODE REVIEW

**Review by gastaldi — COMMENTED** [review]
Why add this offset? Because of Mission control?

**Comment by edewit** [comment]
right and it's the default that the front-end uses

**Comment by gastaldi** [comment]
Interesting, `npm start` runs on port 8088 for me

**Comment by edewit** [comment]
that is true, but it will request `http://localhost:8180/launchpad/commands/launchpad-new-project/next` if you don't specify anything. We could leave it off if you think it's better to always specify the location of the backend with an environment variable.

**Comment by gastaldi** [comment]
I think that's fine. I didn't know about that and always set the env variable before starting the frontend.

**Pull request merged**
